apiVersion: v1
kind: Service
metadata:
  name: users-sqlserver
  namespace: fiap-cloud-games
  labels:
    app: users-sqlserver
spec:
  type: ClusterIP
  selector:
    app: users-sqlserver
  ports:
    - name: sqlserver
      port: 1433
      targetPort: sqlserver
