apiVersion: v1
kind: Secret
metadata:
  name: catalog-mongodb-secret
  namespace: fiap-cloud-games
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: fcg-local-mongo-root
  MONGO_INITDB_DATABASE: FiapCloudGamesCatalog
  FCG_MONGODB_PASSWORD: fcg-local-mongo
