apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: fiap-cloud-games
data:
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong-database
  KONG_PG_PORT: "5432"
  KONG_PG_DATABASE: kong
  KONG_PG_USER: kong
