apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: fiap-cloud-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: wait-migrations
          image: kong:3.9.3
          command: [sh, -ec, "until kong migrations list; do sleep 2; done"]
          envFrom:
            - configMapRef:
                name: kong-config
            - secretRef:
                name: kong-secret
      containers:
        - name: kong
          image: kong:3.9.3
          envFrom:
            - configMapRef:
                name: kong-config
            - secretRef:
                name: kong-secret
          env:
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_ADMIN_GUI_LISTEN
              value: "off"
            - name: KONG_STATUS_LISTEN
              value: 0.0.0.0:8100
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
          ports:
            - name: proxy
              containerPort: 8000
            - name: admin
              containerPort: 8001
            - name: status
              containerPort: 8100
          startupProbe:
            httpGet:
              path: /status
              port: status
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status/ready
              port: status
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: status
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
