apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-configmap
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  Api__UseDeveloperExceptionPage: "false"
  MongoDb__ConnectionString: mongodb://catalog-mongodb:27017
  MongoDb__Username: fcg-catalog
  MongoDb__DatabaseName: FiapCloudGamesCatalog
  MongoDb__CollectionName: game_details
  MongoDb__OperationTimeoutSeconds: "2"
  Redis__Enabled: "true"
  Redis__Configuration: catalog-redis:6379
  Jwt__Issuer: FiapCloudGames
  Jwt__Audience: FiapCloudGames
  Jwt__ExpirationMinutes: "60"
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: /
