apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fiap-cloud-games
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          env:
            - name: RABBITMQ_NODENAME
              value: rabbit@localhost
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          startupProbe:
            tcpSocket:
              port: amqp
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
